import test from 'node:test';import assert from 'node:assert/strict';
import{newEconomy,cleanEconomy,accept,collect,deliver,cancel,buy,ITEMS}from'../src/economy.js';
import{STEPS,DONE,STORY_REVISION,storyOffers,storyAt,storiesAt,availableScenes,completeChapterStep,syncChapter,chapterGuide,discoveredEvidence,canInvestigate,claimRelationship,tamiyaUnlocked,sceneLines}from'../src/story.js';
import{validateSave}from'../src/save.js';import{normalizeLine,PORTRAITS,showPortrait}from'../src/dialogue-portraits.js';
import{opening,branch,prepared,registered,scene,job,race}from'./chapter-helpers.js';
import{NPCS,RESIDENTS}from'../src/cast.js';import{CROWD}from'../src/crowds.js';
const save=e=>({version:4,who:e.chapter.who,name:'Aie',story:e.chapter.step,x:0,z:0,...e,clock:{day:4,minute:900}});
for(const order of [['A','B','C'],['A','C','B'],['B','A','C'],['B','C','A'],['C','A','B'],['C','B','A']])test('all branch orders converge with independent evidence: '+order.join(' → '),()=>{
 let e=prepared(order);assert.equal(e.chapter.paid.length,16);assert.ok(storyAt(e,17,'hakim'));assert.ok(e.chapter.evidence.includes('E15'));assert.equal(e.chapter.evidence.includes('E19'),false);scene(e,'S20');assert.equal(e.chapter.evidence.includes('E18'),true);assert.equal(completeChapterStep(e,'S21','Aie',4),false);job(e,'D17');scene(e,'S21');job(e,'D18');scene(e,'S22');e=validateSave(save(e));assert.ok(e.chapter.completed.includes('S22'));assert.ok(e.chapter.evidence.includes('E19'));assert.equal(e.chapter.tournamentWon,false);assert.equal(e.collection.nostalgia_T01,undefined);
});
test('Amir and Nur begin with the correct mother and home; named crowd speakers retain their existing bodies',()=>{
 for(const who of ['amir','nur']){const e=newEconomy();e.chapter.who=who;assert.equal(chapterGuide(0,e).target.place,who==='amir'?1:11);const s=storyAt(e,who==='amir'?1:11,null);assert.ok(s);assert.equal(sceneLines(e,s)[0].speaker,who==='amir'?'zaitun':'aminah');scene(e,'S01');assert.equal(storyOffers(0,e)[0].from,who==='amir'?1:11);}
 assert.deepEqual(['hakim','keong','ravi'].map(k=>CROWD[k].name),['Badrul','Johnny','Logeswaran']);assert.equal(NPCS.meiling.post,25);assert.equal(NPCS.meiling.role.includes('registrar'),true);
});
test('evidence requires selected supporting cards and a justified conclusion; wrong answers cost nothing',()=>{
 const e=prepared();e.chapter.completed=e.chapter.completed.filter(x=>!x.startsWith('deduce'));const s=STEPS.find(s=>s.id==='deduceA'),before=JSON.stringify(e);
 for(const proof of [undefined,{answer:'wrong0',cards:['E01','E04','E03']},{answer:'A',cards:['E01']},{answer:'A',cards:['E02','E05','E17']}]){assert.equal(canInvestigate(e,s,proof),false);assert.equal(completeChapterStep(e,s.on,'Aie',4,proof),false);assert.equal(JSON.stringify(e),before);}
 assert.ok(canInvestigate(e,s,{answer:'A',cards:['E01','E04','E06']}));assert.ok(completeChapterStep(e,s.on,'Aie',4,{answer:'A',cards:['E01','E04','E06']}));assert.equal(completeChapterStep(e,s.on,'Aie',4,{answer:'A',cards:['E01','E04','E06']}),false);
});
test('delivery offers are prepaid, distinct, restart after cancel, and pay only once',()=>{
 const e=newEconomy();scene(e,'S01');const o=storyOffers(0,e)[0];assert.equal(o.cost,0);assert.equal(o.upah,80);assert.equal(o.item,'story_D01');let j=accept(e,o).job;assert.deepEqual(storyOffers(0,e),[]);collect(e,j.id,j.from);assert.ok(cancel(e,j.id,j.from).ok);assert.deepEqual(e.bag,{});assert.equal(e.chapter.completed.includes('D01'),false);j=accept(e,o).job;collect(e,j.id,j.from);deliver(e,j.id,j.to);const wallet=e.wallet;assert.equal(deliver(e,j.id,j.to).ok,false);assert.equal(accept(e,o).reason,'taken');assert.equal(e.wallet,wallet);assert.equal(storyOffers(0,e).some(x=>x.id===o.id),false);
});
test('practice is the only required learning session; losses qualify and old races do not skip it',()=>{
 const e=newEconomy();e.chapter.completed=['S01','D01','S02','D02','S03','D03'];e.tamiya.played=9;scene(e,'S04');assert.ok(tamiyaUnlocked(e));syncChapter(0,e);assert.equal(e.chapter.completed.includes('training'),false);assert.equal(e.chapter.baseline,9);race(e,'jaguh',false,'fast');assert.equal(e.tamiya.won,0);assert.ok(e.chapter.completed.includes('training'));assert.ok(availableScenes(e).some(s=>s.id==='S05'));
});
test('Chapter 1 reserves adult keepsakes and ends only after the tournament certificate and prize',()=>{
 const e=registered();assert.equal(e.chapter.paid.length,19);assert.equal(e.chapter.paid.reduce((n,id)=>n+STEPS.find(s=>s.id===id).delivery.upah,0),2560);assert.equal(completeChapterStep(e,'S25','Aie',4),false);assert.equal(storyOffers(0,e).some(j=>j.story==='c1-D20'),false);e.chapter.tournamentWon=true;syncChapter(0,e);job(e,'D20');scene(e,'S25');assert.equal(e.chapter.step,DONE);assert.equal(e.chapter.paid.reduce((n,id)=>n+STEPS.find(s=>s.id===id).delivery.upah,0),2680);assert.equal(e.collection.nostalgia_T01,1);const after=JSON.stringify(e);assert.equal(completeChapterStep(e,'S25','Aie',4),false);assert.equal(JSON.stringify(e),after);for(const id of ['nostalgia_I01','nostalgia_I03','nostalgia_I05'])assert.equal(e.collection[id],undefined);assert.ok(storyAt(e,6,null));
});
test('relationship relays use one parcel, require all stops and keep gifts separate from payment',()=>{
 let e=registered();const o=storyOffers(0,e).find(o=>o.story==='c1-R01');assert.equal(o.qty,1);let j=accept(e,o).job;collect(e,j.id,j.from);const wallet=e.wallet;assert.equal(deliver(e,j.id,36).paid,0);assert.equal(e.bag[j.item],1);e=cleanEconomy(e);j=e.jobs[0];assert.equal(j.left,1);assert.equal(deliver(e,j.id,15).paid,120);assert.equal(e.wallet,wallet+120);assert.equal(e.collection.nostalgia_G04,undefined);assert.ok(claimRelationship(e,'nostalgia_G04','Aie',4).ok);assert.equal(claimRelationship(e,'nostalgia_G04','Aie',4).ok,false);job(e,'R02');assert.ok(claimRelationship(e,'nostalgia_M02','Aie',4).ok);assert.equal(e.collection.nostalgia_M02,1);
});
test('Digimon requires three completed post-delivery practice tracks; Tamagotchi two distinct game days',()=>{
 let e=registered();job(e,'R03');assert.equal(claimRelationship(e,'nostalgia_G02','Aie',4).reason,'tracks');for(const t of ['oval','eight','jaguh'])race(e,t);assert.ok(claimRelationship(e,'nostalgia_G02','Aie',4).ok);job(e,'R05');assert.equal(claimRelationship(e,'nostalgia_G03','Aie',4).reason,'day');e.chapter.haniDay=4;e=cleanEconomy(e);assert.equal(claimRelationship(e,'nostalgia_G03','Aie',4).reason,'day');assert.ok(claimRelationship(e,'nostalgia_G03','Aie',5).ok);
});
test('Charizard requires consent and two ordinary duplicates; gift cannot be exchanged or repeated',()=>{
 const e=registered();job(e,'R04');e.collection.kad=2;assert.equal(claimRelationship(e,'nostalgia_P05','Aie',4,{cards:['kad','kad'],confirm:true}).reason,'duplicates');e.collection.kad=3;assert.equal(claimRelationship(e,'nostalgia_P05','Aie',4,{cards:['nostalgia_G04','kad'],confirm:true}).ok,false);assert.equal(claimRelationship(e,'nostalgia_P05','Aie',4,{cards:['kad','kad']}).ok,false);assert.ok(claimRelationship(e,'nostalgia_P05','Aie',4,{cards:['kad','kad'],confirm:true}).ok);assert.equal(e.collection.kad,1);e.collection.kad=3;assert.equal(claimRelationship(e,'nostalgia_P05','Aie',4,{cards:['kad','kad'],confirm:true}).ok,false);assert.equal(e.collection.kad,3);
});
test('revision migration retains wallet, ordinary work, collections and previously earned unique items',()=>{
 const e=registered();job(e,'R01');claimRelationship(e,'nostalgia_G04','Aie',4);e.wallet=5000;e.collection.guli=2;const j=accept(e,{id:'ordinary',kind:'purchase',requester:22,from:25,to:12,stops:[12],item:'gula',qty:1,cost:80,upah:120}).job;collect(e,j.id,25);const raw=save(e);raw.chapter={revision:2,step:22,baseline:0};const old=accept(e,{id:'retired',story:'c1-old',kind:'purchase',requester:6,from:25,to:32,stops:[32],item:'kotak',qty:1,cost:100,upah:100}).job;collect(e,old.id,25);raw.jobs=e.jobs;raw.bag=e.bag;raw.wallet=e.wallet;const r=validateSave(raw);assert.ok(r.upgraded);assert.equal(r.story,0);assert.equal(r.wallet,e.wallet+100);assert.equal(r.collection.guli,2);assert.equal(r.collection.nostalgia_G04,1);assert.deepEqual(r.jobs.map(x=>x.id),[j.id]);assert.equal(r.bag.kotak,undefined);assert.equal(r.bag.gula,1);assert.deepEqual(discoveredEvidence(r),[]);
});
test('all chapter lines use real speakers; character portraits show and notifications stay hidden',()=>{
 const keys=new Set(['player','mother','notification',...Object.keys(NPCS),...Object.keys(CROWD),...Object.values(RESIDENTS).map(r=>r.key)]);for(const s of STEPS)for(const l of s.lines||[])assert.ok(keys.has(l.speaker),l.speaker);assert.doesNotMatch(JSON.stringify(STEPS),/RM30|Rizal|\bLan\b/);const s={who:'nur',name:'Aina'};assert.equal(normalizeLine({speaker:'player',text:'Saya {name}.'},null,s).name,'Aina');assert.equal(normalizeLine({speaker:'hakim',text:'Hai'},null,s).name,'Badrul');const el={hidden:false,style:{},removeAttribute(){},setAttribute(){}};showPortrait(el,'nur');assert.equal(el.hidden,false);showPortrait(el,'farid');assert.equal(el.hidden,false);showPortrait(el,'notification');assert.equal(el.hidden,true);
});
