import test from 'node:test';
import assert from 'node:assert/strict';
import {newEconomy,cleanEconomy,accept,collect,deliver} from '../src/economy.js';
import {NOSTALGIA_QUESTS as qs,startNostalgia,followNostalgiaClue,recordNostalgiaWin,claimNostalgia} from '../src/nostalgia-quests.js';
import {discoveredMemories,memoryJournal,memoryTasks,deliveryTasks} from '../src/journal.js';
import {chapterGuide} from '../src/story.js';
const context=id=>({place:qs[id].place,npc:qs[id].npc});
function start(id='nostalgia_M01'){const e=newEconomy();startNostalgia(e,id,context(id));return e;}
function trust(e,id){for(let i=0;i<qs[id].grind.deliveries;i++){const job=accept(e,{id:'test-'+i,kind:'parcel',requester:22,from:22,to:1+i%18,stops:[1+i%18],item:'gula',qty:1,cost:0,upah:100,route:90}).job;collect(e,job.id,22);deliver(e,job.id,job.to);}}
test('undiscovered quests have no journal tasks or destination marker',()=>{const e=newEconomy();assert.deepEqual(discoveredMemories(e),[]);assert.equal(memoryJournal(e,'nostalgia_M01'),null);assert.deepEqual(memoryTasks(e,'nostalgia_M01'),[]);assert.equal(chapterGuide(7,e).target,null);assert.doesNotMatch(chapterGuide(7,e).text,/six|Faiz|Plan B/i);});
test('delivery requirements tick independently and survive save cleaning',()=>{const e=start(),p=e.nostalgia.quests.nostalgia_M01;p.deliveries=12;p.destinations=[2];p.long=0;const tasks=memoryTasks(e,'nostalgia_M01');assert.deepEqual(tasks.map(t=>t.done),[true,false,false]);assert.equal(tasks[0].current,12);assert.deepEqual(memoryTasks(cleanEconomy(e),'nostalgia_M01'),tasks);});
test('the clue checklist contains completed clues and only the next known stop',()=>{const id='nostalgia_M01',e=start(id);trust(e,id);assert.equal(e.nostalgia.quests[id].stage,'trail');let j=memoryJournal(e,id);assert.deepEqual(j.tasks.filter(t=>t.place).map(t=>t.place),[qs[id].trail[0].place]);assert.ok(!j.tasks.some(t=>t.id.startsWith('win')));followNostalgiaClue(e,id,qs[id].trail[0].place);j=memoryJournal(e,id);assert.deepEqual(j.tasks.filter(t=>t.place).map(t=>t.done),[true,false]);assert.equal(j.note,qs[id].trail[0].clue);assert.deepEqual(memoryJournal(cleanEconomy(e),id),j);});
test('Tamiya wins tick while missing tracks remain open; claim ticks only after earning',()=>{const id='nostalgia_T01',e=start(id);trust(e,id);for(const t of qs[id].trail)followNostalgiaClue(e,id,t.place);for(let i=0;i<6;i++)recordNostalgiaWin(e,{game:'tamiya',track:'oval'});let tasks=memoryTasks(e,id);assert.equal(tasks.find(t=>t.id==='win-0').done,true);assert.deepEqual(tasks.filter(t=>t.id.startsWith('track-')).map(t=>t.done),[true,false,false]);assert.equal(e.nostalgia.quests[id].stage,'challenge');for(const track of ['eight','jaguh'])recordNostalgiaWin(e,{game:'tamiya',track});assert.equal(memoryTasks(e,id).find(t=>t.id==='claim').done,false);claimNostalgia(e,id,context(id),0,'Aie',4);assert.equal(memoryTasks(e,id).find(t=>t.id==='claim').done,true);assert.deepEqual(memoryJournal(cleanEconomy(e),id),memoryJournal(e,id));});
test('multi-stop delivery checklist records pickup and individual completed stops',()=>{const e=newEconomy(),job=accept(e,{id:'multi',kind:'parcel',requester:22,from:22,to:3,stops:[1,2,3],item:'gula',qty:3,cost:0,upah:200,route:90}).job;assert.deepEqual(deliveryTasks(job).map(t=>t.done),[false,false,false,false]);collect(e,job.id,22);deliver(e,job.id,1);assert.deepEqual(deliveryTasks(job).map(t=>t.done),[true,true,false,false]);assert.deepEqual(deliveryTasks(cleanEconomy(e).jobs[0]),deliveryTasks(job));});
