import test from'node:test';import assert from'node:assert/strict';
import{registered,race}from'./chapter-helpers.js';import{newEconomy,cleanEconomy,buy}from'../src/economy.js';import{startTournament,nextTournamentTrack,tournamentTable,settleTournamentRace,cleanTournament}from'../src/tamiya-tournament.js';import{startTamiya,recordTamiya,equipTamiya}from'../src/tamiya-progress.js';import{prepareTamiya,launchTamiya,advanceTamiya,beginPit,rejoinPit}from'../src/tamiya.js';import{STOCK_BUILD}from'../src/tamiya-parts.js';
test('entry requires registration, training cannot score and retries have no entry fee',()=>{const e=newEconomy();assert.throws(()=>startTournament(e));const ready=registered(),wallet=ready.wallet;startTournament(ready);assert.equal(ready.wallet,wallet);assert.equal(nextTournamentTrack(ready),'oval');assert.throws(()=>startTamiya(ready,'jaguh','tamiya','stable',true));race(ready,'eight');assert.equal(ready.tamiya.tournament.run.rounds.length,0);});
test('RM9.50 tyres/brake on the free loaner can win the complete three-track tournament',()=>{let e=registered();const baseline=e.wallet;assert.ok(buy(e,25,'mini_tyres_sponge').ok);assert.ok(buy(e,25,'mini_brake_soft').ok);assert.equal(e.wallet,baseline-950);equipTamiya(e,'tamiya',{...STOCK_BUILD,tyres:'mini_tyres_sponge',brake:'mini_brake_soft'});startTournament(e);const before=e.wallet;for(const track of ['oval','eight','jaguh']){assert.equal(nextTournamentTrack(e),track);race(e,track,true);e=cleanEconomy(e);assert.deepEqual(recordTamiya(e,4),[]);}assert.equal(e.tamiya.tournament.run.winner,'player');assert.ok(e.chapter.tournamentWon);assert.equal(e.wallet,before+300);const table=tournamentTable(e.tamiya.tournament.run);assert.equal(table[0].key,'player');assert.equal(table[0].points,13);assert.equal(table.length,5);const won=e.chapter.tournamentWon;startTournament(e);assert.equal(e.wallet,before+300);assert.equal(e.chapter.tournamentWon,won);});
test('race and pit reload preserve the tournament tag, round standings and completed case',()=>{let e=registered();startTournament(e);race(e,'oval',true);startTamiya(e,'eight','tamiya','stable',true);e.tamiya.round=advanceTamiya(launchTamiya(prepareTamiya(e.tamiya.round),.5),8);e.tamiya.round=beginPit(e.tamiya.round);e=cleanEconomy(e);assert.equal(e.tamiya.round.tournamentRun,e.tamiya.tournament.run.id);assert.equal(e.tamiya.tournament.run.rounds.length,1);assert.ok(e.chapter.completed.includes('S22'));e.tamiya.round=advanceTamiya(e.tamiya.round,2);e.tamiya.round=rejoinPit(e.tamiya.round);e.tamiya.round=advanceTamiya(e.tamiya.round,600);recordTamiya(e,4);assert.equal(e.tamiya.tournament.run.rounds.length,2);const money=e.wallet;assert.deepEqual(recordTamiya(e,4),[]);assert.equal(e.wallet,money);});
test('loss payments are bounded, quit gives no result and evidence persists',()=>{let e=registered();const before=e.wallet;for(let n=0;n<5;n++){startTournament(e);for(const t of ['oval','eight','jaguh'])race(e,t,true,'fast');assert.notEqual(e.tamiya.tournament.run.winner,'player');e=cleanEconomy(e);}assert.equal(e.wallet,before+150);assert.equal(e.tamiya.tournament.lossPaid,3);assert.equal(e.chapter.tournamentWon,false);assert.ok(e.chapter.evidence.includes('E19'));startTournament(e);startTamiya(e,'oval','tamiya','balanced',true);e.tamiya.round=null;assert.deepEqual(recordTamiya(e,4),[]);assert.equal(e.tamiya.tournament.run.rounds.length,0);});
test('equal points compare total time and exact ties trigger a real Eight decision race',()=>{
 const orders=[['player','faiz','keong','hakim','ravi'],['faiz','keong','player','hakim','ravi'],['keong','player','faiz','hakim','ravi']];
 for(const exact of [false,true]){const e=registered();startTournament(e);const r=e.tamiya.tournament.run,money=e.wallet;orders.forEach((order,i)=>settleTournamentRace(e,{id:100+i,track:['oval','eight','jaguh'][i],tournamentRun:r.id},order.map((key,rank)=>({key,duration:30+rank+(exact?0:key==='faiz'?.1:key==='keong'?.2:0)})),4));const table=tournamentTable(r);assert.deepEqual(table.slice(0,3).map(x=>x.points),[10,10,10]);if(exact){assert.equal(r.phase,'tiebreak');assert.deepEqual(new Set(r.ties),new Set(['player','faiz','keong']));assert.equal(r.winner,null);assert.equal(e.wallet,money);assert.equal(nextTournamentTrack(e),'eight');settleTournamentRace(e,{id:200,track:'eight',tournamentRun:r.id},['player','faiz','keong','hakim','ravi'].map((key,i)=>({key,duration:30+i})),4);assert.equal(r.tiebreaks,1);}assert.equal(r.phase,'result');assert.equal(r.winner,'player');assert.equal(e.wallet,money+300);assert.ok(cleanTournament(e.tamiya.tournament).run);}
});
