import { REWARD_STORIES } from './chapter-data.js?v=2.14.0';
// Researched era references; personal stories are fictional game quests.
// Reward-only items are never ordinary shop stock.
export const NOSTALGIA_ITEMS = {
  "nostalgia_M01": {
    "id": "nostalgia_M01",
    "sourceId": "M01",
    "name": "Too Phat - Plan B",
    "title": "Too Phat - Plan B",
    "era": "2001",
    "referenceType": "Album cover reference",
    "image": "./assets/nostalgia/M01.webp",
    "memory": "Malaysian hip-hop album. Digital cover artwork shown; physical CD/cassette packaging may vary.",
    "storyTitle": "The Verse Nobody Heard",
    "story": "Faiz has a notebook of schoolyard rhymes but refuses to perform. Find his former rhyme partner using three familiar town landmarks, then let Faiz choose a private rehearsal or the community stage. His spare Plan B album becomes your reward for helping him find his voice.",
    "inscription": "Given by Faiz after our first rehearsal.",
    "source": "https://music.apple.com/us/album/plan-b/1480794023",
    "photoSource": "https://open.spotify.com/track/6hZUnjbD48g6FBN3c5xS2x",
    "credit": "Spotify / Too Phat, via Anak Ayam track",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_M02": {
    "id": "nostalgia_M02",
    "sourceId": "M02",
    "name": "Too Phat - Whutthadilly?",
    "title": "Too Phat - Whutthadilly?",
    "era": "1999",
    "referenceType": "Album cover reference",
    "image": "./assets/nostalgia/M02.webp",
    "memory": "The debut album's colourful artwork makes a distinct companion to Plan B. Cover reference, not a photographed physical copy.",
    "storyTitle": "Side A, Side B",
    "story": "An argument about who discovered Too Phat first has lasted longer than either friend admits. Compare an old receipt, a handwritten dedication and their conflicting accounts. The dedication reveals they bought the album together. They settle the argument and give you the spare copy they had forgotten.",
    "inscription": "The album that ended a very old argument.",
    "source": "https://music.apple.com/my/album/whutthadilly/723845818",
    "photoSource": "https://music.apple.com/my/album/whutthadilly/723845818",
    "credit": "Apple Music / EMI Malaysia",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_M03": {
    "id": "nostalgia_M03",
    "sourceId": "M03",
    "name": "Butterfingers - Transcendence",
    "title": "Butterfingers - Transcendence",
    "era": "1999",
    "referenceType": "Album cover reference",
    "image": "./assets/nostalgia/M03.webp",
    "memory": "A Malaysian alternative-rock collection item. The sepia artwork would stand out on a bedroom music shelf.",
    "storyTitle": "One More Soundcheck",
    "story": "Behind the barber's mirror is a photograph of his former school band. Help identify the members, invite them to the balai raya and arrange a rehearsal without promising a perfect performance. Their reunion earns a Transcendence album from his duplicate collection and adds their band photo to the event board.",
    "inscription": "A thank-you from the band behind the mirror.",
    "source": "https://music.apple.com/id/album/transcendence/749724021",
    "photoSource": "https://music.apple.com/id/album/transcendence/749724021",
    "credit": "Apple Music / Butterfingers",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_M04": {
    "id": "nostalgia_M04",
    "sourceId": "M04",
    "name": "Siti Nurhaliza - Pancawarna",
    "title": "Siti Nurhaliza - Pancawarna",
    "era": "1999",
    "referenceType": "Album cover reference",
    "image": "./assets/nostalgia/M04.webp",
    "memory": "Malaysian pop album with its recognisable portrait-panel artwork. Use this as the edition reference before making a physical case.",
    "storyTitle": "A Song at the Sewing Table",
    "story": "Normah remembers playing Pancawarna while sewing her daughter's school uniform. Recover a misplaced family photo and identify the uniform from a fabric sample. Help assemble a small family display for Malam Kenangan. Her spare album carries a new handwritten dedication to you.",
    "inscription": "For the helper who remembered the little details.",
    "source": "https://music.apple.com/us/song/574352076",
    "photoSource": "https://www.shazam.com/song/574352076/seribu-kemanisan",
    "credit": "Shazam / Suria Records",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_M05": {
    "id": "nostalgia_M05",
    "sourceId": "M05",
    "name": "Lagi Lagi Senario VCD",
    "title": "Lagi Lagi Senario VCD",
    "era": "2001 film",
    "referenceType": "Physical media photo",
    "image": "./assets/nostalgia/M05.webp",
    "memory": "A photographed Malaysian VCD release. Film year is verified; the particular packaging's manufacturing date is not established.",
    "storyTitle": "Everybody Bring a Chair",
    "story": "The town's Senario movie night keeps failing because everyone assumes someone else has the chairs, cables or screen. Arrange the seating and track down the missing AV cable before evening. The neighbours finally watch together; Kak Ita gives you her extra VCD case after the screening.",
    "inscription": "The night the whole row laughed together.",
    "source": "https://browse.tonton.com.my/movie/lagi-lagi-senario",
    "photoSource": "https://www.carousell.com.my/p/senario-vcd-1250424376/",
    "credit": "Carousell seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P01": {
    "id": "nostalgia_P01",
    "sourceId": "P01",
    "name": "GEMPAK - January 1999",
    "title": "GEMPAK - January 1999",
    "era": "1999 issue",
    "referenceType": "Magazine cover reference",
    "image": "./assets/nostalgia/P01.webp",
    "memory": "An early Malaysian info-comics magazine cover. The publisher dates GEMPAK's launch to 1998.",
    "storyTitle": "The Drawing in the Margin",
    "story": "A pencilled cartoon tucked into a GEMPAK issue resembles a mural that was never finished. Match its details to places around town and find the shy resident who drew it. With permission, display a copy at the library. Azura gives you a duplicate January 1999 issue.",
    "inscription": "A small drawing that deserved to be seen.",
    "source": "https://gempakstarz.com/about-us-malaysia-top-publisher/",
    "photoSource": "https://murai.my/setelah-lebih-2-dekad-majalah-gempak-umum-tamatkan-perkhidmatan/",
    "credit": "Murai MY article image",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P02": {
    "id": "nostalgia_P02",
    "sourceId": "P02",
    "name": "UJANG - No. 111",
    "title": "UJANG - No. 111",
    "era": "15 February 1999",
    "referenceType": "Vintage magazine photo",
    "image": "./assets/nostalgia/P02.webp",
    "memory": "The dated cover is the reference: a specific issue, rather than an invented generic Ujang magazine.",
    "storyTitle": "Superhero of the School Bag",
    "story": "Farid remembers a student who passed this Ujang issue around after a difficult week. Three residents remember different parts of the incident. Piece their accounts together and organise a lunchtime comic swap. The old circulation notebook finally gains a returned stamp, and a spare issue becomes yours.",
    "inscription": "Borrowed laughter, finally returned.",
    "source": "https://shopee.com.my/MAJALAH-LAWAK-ANTARABANGSA-UJANG-NO.111-120-%28PRELOVED-MAJALAH-UJANG-MOY-KOMIK-LAMA%29-i.38847796.21329359637",
    "photoSource": "https://shopee.com.my/MAJALAH-LAWAK-ANTARABANGSA-UJANG-NO.111-120-%28PRELOVED-MAJALAH-UJANG-MOY-KOMIK-LAMA%29-i.38847796.21329359637",
    "credit": "Shopee vintage-magazine seller",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P03": {
    "id": "nostalgia_P03",
    "sourceId": "P03",
    "name": "APO? - No. 3",
    "title": "APO? - No. 3",
    "era": "February 1999",
    "referenceType": "Vintage magazine photo",
    "image": "./assets/nostalgia/P03.webp",
    "memory": "A dated early issue with its original cover design. Issue/date identification comes from the photographed collectible and seller description.",
    "storyTitle": "The Joke That Travelled",
    "story": "The bus driver has retold a joke for years but forgotten who lent him the APO? issue. Reconstruct its journey from the bus station to the warung and library. Return the borrowed original to its owner. Pak Karim buys you another copy as thanks for finishing the longest loan in town.",
    "inscription": "A joke with more stops than the bus.",
    "source": "https://www.mudah.my/majalah-apo-no-3-feb-1999-vintage-komik-magazine-114531813.htm",
    "photoSource": "https://www.mudah.my/majalah-apo-no-3-feb-1999-vintage-komik-magazine-114531813.htm",
    "credit": "Mudah.my seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P04": {
    "id": "nostalgia_P04",
    "sourceId": "P04",
    "name": "Dragon Ball / Mutiara Naga",
    "title": "Dragon Ball / Mutiara Naga",
    "era": "1990s reading culture",
    "referenceType": "Malay-edition photo",
    "image": "./assets/nostalgia/P04.webp",
    "memory": "Local-language comic reference from a second-hand listing. Exact volume and printing year need an inside-page check.",
    "storyTitle": "Cepat! Son Goku",
    "story": "Faiz and a former classmate stopped talking over a borrowed Mutiara Naga volume. Read their names inside the cover and find the missing explanation in an old school note. Give them a chance to speak without taking sides. They lend the original to the library and gift you a duplicate.",
    "inscription": "A comic returned, a friendship reopened.",
    "source": "https://gempak.com/rojakdaily/entertainment/7-comics-and-magazines-we-used-read-kids-malaysia-56894",
    "photoSource": "https://shopee.com.my/PRELOVED-Komik-Manga-Mutiara-Naga-Dragon-Ball-Karya-Akira-Toriyama-%28Comic-House%29-i.64519384.23636819840",
    "credit": "Shopee second-hand comic seller",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P05": {
    "id": "nostalgia_P05",
    "sourceId": "P05",
    "name": "Pokemon Base Set - Charizard",
    "title": "Pokemon Base Set - Charizard",
    "era": "1999 English Base Set",
    "referenceType": "Vintage card photo",
    "image": "./assets/nostalgia/P05.webp",
    "memory": "Unlimited holographic 4/102 reference. This is not the 2021 Celebrations reprint; seller attribution is not an authentication certificate.",
    "storyTitle": "The Trade We Both Remember",
    "story": "Two collectors remember a childhood Charizard trade differently. Inspect their collection lists and let each explain what the card meant to them. They choose a fair new exchange themselves. Mei Ling rewards your help with a separately verified spare card; its provenance stays in your collection entry.",
    "inscription": "Earned through trust, with its own history.",
    "source": "https://renewantiques.com/product/original-1999-pokemon-base-set-charizard-4-102-unlimited-holo-foil-game-card-pokemon-tcg-game-card-nm/",
    "photoSource": "https://renewantiques.com/product/original-1999-pokemon-base-set-charizard-4-102-unlimited-holo-foil-game-card-pokemon-tcg-game-card-nm/",
    "credit": "Renew Antiques product photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P06": {
    "id": "nostalgia_P06",
    "sourceId": "P06",
    "name": "Pokemon four-pocket binder",
    "title": "Pokemon four-pocket binder",
    "era": "Late-1990s reference",
    "referenceType": "Vintage binder photo",
    "image": "./assets/nostalgia/P06.webp",
    "memory": "A real photographed card album with familiar characters. Seller identifies it as a 1999 Nintendo/WOTC item; exact edition remains to be checked.",
    "storyTitle": "An Empty Pocket for a Friend",
    "story": "Mei Ling's binder has one deliberately empty pocket. It was reserved for a friend who moved away. Find the friend's new contact through family conversations and arrange a letter exchange. Mei Ling keeps her original binder and gives you a spare, with its first pocket reserved for your shared photo.",
    "inscription": "The first pocket is for a friendship.",
    "source": "https://www.ebay.com/itm/178030558364",
    "photoSource": "https://www.ebay.com/itm/178030558364",
    "credit": "eBay seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_P07": {
    "id": "nostalgia_P07",
    "sourceId": "P07",
    "name": "Panini - France 98 album",
    "title": "Panini - France 98 album",
    "era": "1998 tournament",
    "referenceType": "Vintage sticker-album photo",
    "image": "./assets/nostalgia/P07.webp",
    "memory": "International World Cup album reference. The photographed cover is not confirmed as a Malaysian retail edition.",
    "storyTitle": "The Last Empty Square",
    "story": "A France 98 sticker album is missing one sticker after years of playground swaps. Organise a swap table, identify duplicate stickers and help collectors agree on trades. Completing the original brings its old classmates back together. Hafiz gives you a second album to begin your own collection.",
    "inscription": "The album we finished together.",
    "source": "https://www.lacasadelasfiguritas.com/products/album-francia-1998-panini-pegado-completo",
    "photoSource": "https://www.lacasadelasfiguritas.com/products/album-francia-1998-panini-pegado-completo",
    "credit": "La Casa de las Figuritas product photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G01": {
    "id": "nostalgia_G01",
    "sourceId": "G01",
    "name": "Nokia 3310 - original blue",
    "title": "Nokia 3310 - original blue",
    "era": "2000",
    "referenceType": "Original handset photo",
    "image": "./assets/nostalgia/G01.webp",
    "memory": "The original monochrome handset, distinct from the 2017 revival. Nokia's launch announcement is dated 1 September 2000.",
    "storyTitle": "A Name Saved as Home",
    "story": "A drawer-held Nokia contains a contact saved only as Home. Kak Lina wants to understand it without losing the old messages. With her permission, use the address-book clues to find the relative who owned it. After preserving the family's messages, she passes the handset to you with a new welcome note.",
    "inscription": "An old phone with a new place to call home.",
    "source": "https://www.globenewswire.com/news-release/2000/09/01/1845525/0/en/nokia-introduces-mobile-chat-with-the-nokia-3310.html",
    "photoSource": "https://mobilenet.cz/clanky/nokia-3310-slavi-20-let-vzpominate-na-hada-ci-ikonicke-vyzvaneni-41570",
    "credit": "Mobilenet.cz article photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G02": {
    "id": "nostalgia_G02",
    "sourceId": "G02",
    "name": "Digimon - Digital Monster",
    "title": "Digimon - Digital Monster",
    "era": "1997 original line",
    "referenceType": "Vintage packaged toy photo",
    "image": "./assets/nostalgia/G02.webp",
    "memory": "A first-generation virtual-pet reference in international packaging. Do not substitute a modern colour-screen device.",
    "storyTitle": "One Last Link Battle",
    "story": "Faiz finds a pair of old Digimon devices but neither has a ready creature. Help both friends care for their pets over several visits, then arrange a friendly link battle. Their reunion matters more than the winner. Faiz gives you the spare device so you can join the next round.",
    "inscription": "The third player in an old rivalry.",
    "source": "https://corp.toei-anim.co.jp/ja/press/press-301417465337941582.html",
    "photoSource": "https://www.ebay.com/itm/125702438088",
    "credit": "eBay seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G03": {
    "id": "nostalgia_G03",
    "sourceId": "G03",
    "name": "Tamagotchi - silver-grey shell",
    "title": "Tamagotchi - silver-grey shell",
    "era": "1997 original generation",
    "referenceType": "Vintage packaged toy photo",
    "image": "./assets/nostalgia/G03.webp",
    "memory": "A photographed original-generation toy, identified by the seller as 1997. Selected instead of a modern anniversary shell.",
    "storyTitle": "Recess Babysitter",
    "story": "Hani uses an old Tamagotchi to explain caring for small things. Look after a spare device while she prepares a school activity, answering its needs at sensible intervals. Return to compare what worked rather than chase a perfect score. She gifts the device with a little care diary.",
    "inscription": "Small things need someone to notice.",
    "source": "https://www.ebay.com/itm/156604420094",
    "photoSource": "https://www.ebay.com/itm/156604420094",
    "credit": "eBay seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G04": {
    "id": "nostalgia_G04",
    "sourceId": "G04",
    "name": "Sony Walkman WM-EX9",
    "title": "Sony Walkman WM-EX9",
    "era": "1998",
    "referenceType": "Original device reference",
    "image": "./assets/nostalgia/G04.webp",
    "memory": "Sony's historical timeline places the WM-EX9 in 1998. Cassette-player and wired-remote reference shown.",
    "storyTitle": "The Tape with No Label",
    "story": "A label-free cassette holds an old family greeting. Help Kamal test his Walkman, then identify familiar voices through conversations rather than invented copyrighted songs. Reunite the recording with the family and preserve their recollections. He gifts you his spare player, keeping the original tape at home.",
    "inscription": "Some voices are worth keeping.",
    "source": "https://www.sony.com/ja/SonyInfo/IR/news/qfhh7c000000hcfy-att/history.pdf",
    "photoSource": "https://www.obsoletesony.com/de/walkman/wm-ex9/",
    "credit": "ObsoleteSony reference photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G05": {
    "id": "nostalgia_G05",
    "sourceId": "G05",
    "name": "Sony Discman D-E301",
    "title": "Sony Discman D-E301",
    "era": "Late 1990s",
    "referenceType": "Original device photo",
    "image": "./assets/nostalgia/G05.webp",
    "memory": "Portable CD player with ESP and Mega Bass. A separate underside photograph documents a December 1998 example.",
    "storyTitle": "Don't Let It Skip",
    "story": "Kak Lina remembers walking to school while trying not to make her Discman skip. Follow her old route, keeping a gentle rhythm and stopping at the places she describes. Returning safely unlocks her school-day account. She gifts the spare player she once kept for a cousin.",
    "inscription": "The route that always needed one more song.",
    "source": "https://spencertified.com/products/sony-discman-d-e301-esp-electronic-shock-protection-cd-portable-compact-player-mega-bass-avls-discman-spencertified",
    "photoSource": "https://spencertified.com/products/sony-discman-d-e301-esp-electronic-shock-protection-cd-portable-compact-player-mega-bass-avls-discman-spencertified",
    "credit": "SpenCertified product photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G06": {
    "id": "nostalgia_G06",
    "sourceId": "G06",
    "name": "PlayStation memory card",
    "title": "PlayStation memory card",
    "era": "Original PlayStation era",
    "referenceType": "Official accessory photo",
    "image": "./assets/nostalgia/G06.webp",
    "memory": "Sony SCPH-1020 memory-card reference with Japanese packaging. Regional packaging differs.",
    "storyTitle": "Slot Two",
    "story": "A memory card bears two siblings' initials. Help its owner identify the correct save without overwriting either file, using playtime and a handwritten notebook. Invite the sibling back for a shared evening. Faiz gives you a separate empty card, labelled with your chosen player name.",
    "inscription": "A blank card for the adventures ahead.",
    "source": "https://www.ebay.co.uk/itm/304522995994",
    "photoSource": "https://www.ebay.co.uk/itm/304522995994",
    "credit": "eBay seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_G07": {
    "id": "nostalgia_G07",
    "sourceId": "G07",
    "name": "Final Fantasy VII - PS1 case",
    "title": "Final Fantasy VII - PS1 case",
    "era": "1997 game",
    "referenceType": "Physical game-case photo",
    "image": "./assets/nostalgia/G07.webp",
    "memory": "NTSC-U/C three-disc edition shown. It is a reference edition, not a claim that this packaging was Malaysia's standard release.",
    "storyTitle": "Before the Final Disc",
    "story": "Faiz saved the last evening of Final Fantasy VII for a friend who moved away. Find an unsent invitation, reconnect the two and organise a shared gaming evening. The quest is about their unfinished ritual, not copying the game's story. A spare original-edition case becomes your keepsake.",
    "inscription": "An adventure is better when someone comes back.",
    "source": "https://www.playstation.com/en-us/playstation-history/1994-ps-one/",
    "photoSource": "https://mx.ebay.com/b/Final-Fantasy-VII-Sony-PlayStation-1-Video-Games/139973/bn_7361802",
    "credit": "eBay seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I01": {
    "id": "nostalgia_I01",
    "sourceId": "I01",
    "name": "KLCC Twin Towers miniature",
    "title": "KLCC Twin Towers miniature",
    "era": "Landmark opened 1999",
    "referenceType": "Modern souvenir reference",
    "image": "./assets/nostalgia/I01.webp",
    "memory": "Real 6-inch souvenir sold by the official tower shop. Its sale today does not establish this exact model existed in 2001.",
    "storyTitle": "The Trip We Never Took",
    "story": "Nenek kept a family plan for a Kuala Lumpur trip that never happened. Help arrange a small travel display from the family's own accounts and postcards. She marks the trip as a future promise rather than a failure. A KLCC miniature becomes your reminder; its model edition must fit the final town timeline.",
    "inscription": "For a journey still waiting to happen.",
    "source": "https://www.petronastwintowers.com.my/the-towers/the-stories/",
    "photoSource": "https://shop.petronastwintowers.com/products/petronas-twin-towers-6-miniature-with-base",
    "credit": "Official PETRONAS Twin Towers shop",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I02": {
    "id": "nostalgia_I02",
    "sourceId": "I02",
    "name": "Wira - Kuala Lumpur 98 mascot",
    "title": "Wira - Kuala Lumpur 98 mascot",
    "era": "1998 Games",
    "referenceType": "Vintage souvenir photo",
    "image": "./assets/nostalgia/I02.webp",
    "memory": "An actual photographed mascot plush with Kuala Lumpur 98 tags. The plush is better evidenced than the earlier suggested figurine.",
    "storyTitle": "The Mascot in the Cupboard",
    "story": "The Wira mascot plush was left behind after a school visit to the 1998 Games. Match a faded class photo to former pupils and discover who was meant to receive it. With the class's agreement, display the original at school. A spare event plush is awarded to you at the reunion.",
    "inscription": "The mascot that brought a class together.",
    "source": "https://www.commonwealthsport.com/news/4322805/do-you-know-your-commonwealth-games-mascots-/",
    "photoSource": "https://www.carousell.com.my/p/wira-the-official-mascot-commonwealth-games-kuala-lumpur-1998-1226928654/",
    "credit": "Carousell seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I03": {
    "id": "nostalgia_I03",
    "sourceId": "I03",
    "name": "Proton Wira miniature",
    "title": "Proton Wira miniature",
    "era": "Car introduced 1993",
    "referenceType": "Modern custom-model reference",
    "image": "./assets/nostalgia/I03.webp",
    "memory": "Photographed 1:24 custom miniature. The modern grey finish and display do not establish a period-manufactured collectible.",
    "storyTitle": "Dad's First Car",
    "story": "A resident remembers the family's first Wira by an old fuel receipt and a scratched photograph. Help Pak Man identify its colour and trim, then commission a small model for the family display. A matching miniature is your reward. Its finish reflects your evidence, not a random rare colour.",
    "inscription": "The little model of a very big first step.",
    "source": "https://www.proton.com/happenings/2024/october/from-saga-to-s70-proton-champions-sedan-sales-in-malaysia",
    "photoSource": "https://shopee.com.my/DIECAST-CUSTOM-PROTON-WIRA-NARDO-GREY-SCALE-1-24-i.54361130.24557897348",
    "credit": "Shopee custom-model seller",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I04": {
    "id": "nostalgia_I04",
    "sourceId": "I04",
    "name": "Perodua Kancil miniature",
    "title": "Perodua Kancil miniature",
    "era": "Car introduced 1994",
    "referenceType": "Vehicle reference / miniature pending",
    "image": "./assets/nostalgia/I04.webp",
    "memory": "A real 1999 Kancil is shown as a body-shape reference. A matching period miniature photograph has not been verified; this is a proposed reward.",
    "storyTitle": "Five People, One Kancil",
    "story": "Kak Lina's family remembers packing a tiny Kancil for a balik kampung trip. Match luggage to their accounts and solve a miniature packing puzzle without placing anyone unsafely in a real car. Her family commissions a Kancil display model to commemorate the trip and gifts you a matching one.",
    "inscription": "Small car, enormous memories.",
    "source": "https://www.perodua.com.my/corporate-branding/milestones",
    "photoSource": "https://www.carlist.my/used-cars/rm2800-1999-perodua-kancil-660-ex-hatchback/4212389",
    "credit": "Carlist.my vehicle photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I05": {
    "id": "nostalgia_I05",
    "sourceId": "I05",
    "name": "Telekom Malaysia phonecards",
    "title": "Telekom Malaysia phonecards",
    "era": "Kuala Lumpur 98 designs",
    "referenceType": "Vintage phonecard photo",
    "image": "./assets/nostalgia/I05.webp",
    "memory": "Two photographed chip phonecards carrying the Commonwealth Games branding. Card designs are the evidence for this selection.",
    "storyTitle": "The Call After School",
    "story": "A Telekom phonecard recalls the day a pupil waited at the bus stop and could not reach home. Follow the old route and speak to the adults who helped. The family records its thanks on the community board. Pak Karim gifts two duplicate Games phonecards from his own collection.",
    "inscription": "A small card that once meant someone was coming.",
    "source": "https://www.carousell.com.my/p/kad-telekom-kuala-lumpur-commonwealth-games-1998-1226347640/",
    "photoSource": "https://www.carousell.com.my/p/kad-telekom-kuala-lumpur-commonwealth-games-1998-1226347640/",
    "credit": "Carousell seller photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I06": {
    "id": "nostalgia_I06",
    "sourceId": "I06",
    "name": "RM1 paper banknote",
    "title": "RM1 paper banknote",
    "era": "Third series - issued 2000",
    "referenceType": "Banknote reference photo",
    "image": "./assets/nostalgia/I06.webp",
    "memory": "BNM issued the new RM1 design on 8 November 2000. Some collector listings label variants differently; use the BNM date for the game timeline.",
    "storyTitle": "My First Ringgit",
    "story": "Rahman remembers the first ringgit he earned helping his father. Complete a careful stock-counting task, then choose how your own first reward is recorded in the shop ledger. He exchanges your ordinary reward note for a keepsake example and writes a personal dedication on its protective sleeve.",
    "inscription": "My first honest ringgit in this town.",
    "source": "https://www.bnm.gov.my/-/new-design-rm1-banknotes",
    "photoSource": "https://www.ebay.com/itm/224442661059",
    "credit": "eBay collector listing photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I07": {
    "id": "nostalgia_I07",
    "sourceId": "I07",
    "name": "RM1 coin - 1990 example",
    "title": "RM1 coin - 1990 example",
    "era": "In circulation during the period",
    "referenceType": "Vintage coin photo",
    "image": "./assets/nostalgia/I07.webp",
    "memory": "A dated hibiscus-design coin. BNM withdrew the RM1 coin on 7 December 2005; it fits a 2001 town.",
    "storyTitle": "The Biscuit Tin Bank",
    "story": "A biscuit tin contains coins saved for a family gathering. Sort the contents and help Nenek reconcile them with a little notebook. One old RM1 coin is a reminder of her grandchild's first contribution. She keeps that original and gives you another dated example for your own collection.",
    "inscription": "The sound of saving a little at a time.",
    "source": "https://www.bnm.gov.my/-/reminder-to-the-public-on-the-withdrawal-of-the-rm1-coin-from-circulation",
    "photoSource": "https://tomorins24.jp/?pid=154732958",
    "credit": "Tomorins24 collector-shop photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_I08": {
    "id": "nostalgia_I08",
    "sourceId": "I08",
    "name": "KL 98 Commonwealth stamps",
    "title": "KL 98 Commonwealth stamps",
    "era": "1998 Games",
    "referenceType": "Vintage stamp-sheet photo",
    "image": "./assets/nostalgia/I08.webp",
    "memory": "A photographed 16-stamp sports sheetlet. Issue identification follows the sheet's printed text and collector listing.",
    "storyTitle": "Letters from the Games",
    "story": "The retired postman finds a folder of letters and a spare KL98 stamp sheet. Read the permitted excerpts, match senders to recipients and help families choose which memories can be shown publicly. Pak Abu gifts the sheet after the letter display opens; private letters stay with their owners.",
    "inscription": "Every stamp once carried somebody's news.",
    "source": "https://www.ebay.com.my/itm/114327699351",
    "photoSource": "https://www.ebay.com.my/itm/114327699351",
    "credit": "eBay collector photograph",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  },
  "nostalgia_T01": {
    "id": "nostalgia_T01",
    "sourceId": "T01",
    "name": "Tamiya Lightning Magnum",
    "title": "Tamiya Lightning Magnum",
    "era": "1999 model",
    "referenceType": "Model-kit photo",
    "image": "./assets/nostalgia/T01.webp",
    "memory": "A photographed Aero Mini 4WD kit, item 19612. Tamiya's official history dates Lightning Magnum to September 1999.",
    "storyTitle": "The Car Behind the Window",
    "story": "Faiz dreams of the Lightning Magnum in Uncle Lim's window but his own racer is unreliable. Help diagnose its setup and complete a fair three-race challenge. Uncle Lim awards the kit as the event prize. A small signed race card records the track and your result beside the model.",
    "inscription": "The car I earned, with the race to prove it.",
    "source": "https://www.tamiya.com/japan/products/19442/index.html",
    "photoSource": "https://shopee.tw/%E3%80%8A1999JC%E6%9C%83%E5%A0%B4%E9%99%90%E5%AE%9A%E3%80%8B%E5%9B%9B%E9%A9%85%E8%BB%8A-TAMIYA-%E7%94%B0%E5%AE%AE-19612-%E7%88%86%E8%B5%B0%E5%85%84%E5%BC%9F-%E6%98%9F%E9%A6%AC%E8%B1%AA-%E4%BA%94%E4%BB%A3-%E9%9B%BB%E5%85%89%E8%A1%9D%E9%8B%92-i.11884020.18527535239",
    "credit": "Shopee Taiwan model-kit seller",
    "kind": "collect",
    "size": 0,
    "price": 0,
    "rewardOnly": true
  }
};

for(const [id,r] of Object.entries(REWARD_STORIES))Object.assign(NOSTALGIA_ITEMS[id],{storyTitle:r.title,story:r.story,inscription:r.memory});
