// The editable town plan. Positions are metres from the town centre; `rot` is
// quarter turns (0–3). The map editor saves this shape; see docs/MAP-EDITOR.md.
export const TOWN_PLAN = {
  "version": 1,
  "units": [
    { "id": "home", "kind": "home", "x": -43, "z": 27, "rot": 0, "places": [1] },
    { "id": "house-2", "kind": "house", "x": -51, "z": -47, "rot": 0, "places": [2] },
    { "id": "house-3", "kind": "house", "x": -37, "z": -47, "rot": 0, "places": [3] },
    { "id": "house-4", "kind": "house", "x": -51, "z": -27, "rot": 0, "places": [4] },
    { "id": "house-5", "kind": "house", "x": -37, "z": -27, "rot": 0, "places": [5] },
    { "id": "house-6", "kind": "house", "x": -51, "z": -11, "rot": 0, "places": [6] },
    { "id": "house-7", "kind": "house", "x": -37, "z": -11, "rot": 0, "places": [7] },
    { "id": "house-8", "kind": "house", "x": -51, "z": 51, "rot": 0, "places": [8] },
    { "id": "wakaf", "kind": "wakaf", "x": -37, "z": 51, "rot": 0, "places": [9] },
    { "id": "pondok", "kind": "pondok", "x": -76, "z": -17, "rot": 0, "places": [10] },
    { "id": "terrace-11", "kind": "terrace", "x": 34, "z": 16, "rot": 0, "places": [11] },
    { "id": "terrace-12", "kind": "terrace", "x": 41, "z": 16, "rot": 0, "places": [12] },
    { "id": "terrace-13", "kind": "terrace", "x": 48, "z": 16, "rot": 0, "places": [13] },
    { "id": "terrace-14", "kind": "terrace", "x": 55, "z": 16, "rot": 0, "places": [14] },
    { "id": "terrace-15", "kind": "terrace", "x": 34, "z": 31, "rot": 0, "places": [15] },
    { "id": "terrace-16", "kind": "terrace", "x": 41, "z": 31, "rot": 0, "places": [16] },
    { "id": "terrace-17", "kind": "terrace", "x": 48, "z": 31, "rot": 0, "places": [17] },
    { "id": "terrace-18", "kind": "terrace", "x": 55, "z": 31, "rot": 0, "places": [18] },
    { "id": "minishop", "kind": "minishop", "x": 70, "z": -10, "rot": 0, "places": [19] },
    { "id": "nursery", "kind": "nursery", "x": 70, "z": 18, "rot": 0, "places": [20] },
    { "id": "warung", "kind": "warung", "x": 12, "z": -6.5, "rot": 0, "places": [21] },
    { "id": "shops", "kind": "shophouses", "x": 17, "z": -24, "rot": 0, "places": [22, 23, 24, 25, 26, 27, 28] },
    { "id": "school", "kind": "school", "x": 4.5, "z": -46, "rot": 0, "places": [29] },
    { "id": "canteen", "kind": "canteen", "x": -12, "z": -36, "rot": 0, "places": [30] },
    { "id": "mosque", "kind": "mosque", "x": 48, "z": -39, "rot": 0, "places": [31] },
    { "id": "hall", "kind": "hall", "x": 38, "z": -56, "rot": 0, "places": [32] },
    { "id": "library", "kind": "library", "x": 52, "z": -56, "rot": 0, "places": [33] },
    { "id": "court", "kind": "court", "x": 11, "z": -36, "rot": 0, "places": [34] },
    { "id": "bus-stop", "kind": "busstop", "x": 52, "z": 39, "rot": 0, "places": [35] },
    { "id": "workshop", "kind": "workshop", "x": 33, "z": 56, "rot": 0, "places": [36] },
    { "id": "petrol", "kind": "petrol", "x": 70, "z": 50, "rot": 0, "places": [37] },
    { "id": "market", "kind": "market", "x": 8, "z": 52, "rot": 0, "places": [38] },
    { "id": "square", "kind": "square", "x": 7, "z": 22, "rot": 0, "places": [] },
    { "id": "bus", "kind": "bus", "x": 53, "z": 51, "rot": 0, "places": [] },
    { "id": "car-red", "kind": "sedan", "x": -13, "z": 10.8, "rot": 1, "places": [], "color": "#d4322c" },
    { "id": "car-white", "kind": "sedan", "x": 21, "z": 10.8, "rot": 3, "places": [], "color": "#eeece4" },
    { "id": "walker-pak", "kind": "passerby", "x": 37, "z": 9, "rot": 0, "places": [], "who": "pak" },
    { "id": "walker-nur", "kind": "passerby", "x": 1, "z": -13, "rot": 0, "places": [], "who": "nur" }
  ],
  "roads": [
    { "id": "main-road", "kind": "asphalt", "x": 0, "z": 4, "w": 150, "d": 8 },
    { "id": "west-road", "kind": "asphalt", "x": -25, "z": 0, "w": 7, "d": 132 },
    { "id": "east-road", "kind": "asphalt", "x": 62, "z": 0, "w": 7, "d": 132 },
    { "id": "kampung-lane", "kind": "dirt", "x": -43, "z": 1, "w": 4, "d": 114 },
    { "id": "kampung-path-south", "kind": "dirt", "x": -44, "z": -36, "w": 30, "d": 3 },
    { "id": "kampung-path-north", "kind": "dirt", "x": -44, "z": -18, "w": 30, "d": 3 },
    { "id": "market-lane", "kind": "dirt", "x": 4, "z": 37, "w": 90, "d": 4 },
    { "id": "pekan-lane", "kind": "dirt", "x": 17, "z": -13, "w": 69, "d": 4 },
    { "id": "warung-path", "kind": "dirt", "x": 29, "z": -1, "w": 4, "d": 30 },
    { "id": "terrace-path-front", "kind": "dirt", "x": 46, "z": 9, "w": 30, "d": 3 },
    { "id": "terrace-path-back", "kind": "dirt", "x": 46, "z": 24, "w": 30, "d": 3 },
    { "id": "market-path", "kind": "dirt", "x": 24, "z": 49, "w": 4, "d": 30 },
    { "id": "bus-path", "kind": "dirt", "x": 39, "z": 43, "w": 32, "d": 3 },
    { "id": "petrol-path", "kind": "dirt", "x": 44, "z": 53, "w": 3, "d": 25 },
    { "id": "hall-path", "kind": "dirt", "x": 40, "z": -48, "w": 4, "d": 8 },
    { "id": "square-path-south", "kind": "dirt", "x": 7, "z": 10.75, "w": 3, "d": 5.5 },
    { "id": "square-path-north", "kind": "dirt", "x": 7, "z": 32.75, "w": 3, "d": 4.5 }
  ]
};
